version: "3.9"
services:
  app:
    build: .
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER={$DB_USER}
      - DB_PASSWORD={$DB_PASSWORD}
      - DB_NAME={$DB_NAME}
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER={$DB_USER}
      - POSTGRES_PASSWORD={$DB_PASSWORD}
      - POSTGRES_DB={$DB_NAME}
